/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo;

import java.awt.Color;
import java.awt.Graphics;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 * Esta Classe é responsável por
 * adicionar as formas no Graphics
 * e redimensionamento de tela
 * 
 * @author Luzia e Roseane
 */
public class Painel extends javax.swing.JPanel {

    private int x1, x2, y1, y2, xTela, yTela;
    private Editor editor;
    
    
    /**
     * Creates new form Painel
     */
    public Painel() {
        initComponents();
        x1=0;
        x2=0;
        y1=0;
        y2=0;
        xTela = 0;
        yTela = 0;
        try {
            editor = new Editor();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro fatal.", "ERRO", WARNING_MESSAGE);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
        x1 = evt.getX();
        y1 = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        
        Graphics g = getGraphics();
        x2 = evt.getX();
        y2 = evt.getY();
        try {
            editor.addFigura(g, x1, x2, y1, y2);
        } catch(CoordNegativa ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", WARNING_MESSAGE);
        }
    }//GEN-LAST:event_formMouseReleased

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        
        xTela = evt.getX();
        yTela = evt.getY();
    }//GEN-LAST:event_formMouseMoved

    @Override
    protected void paintComponent(Graphics g) {
       
        super.paintComponent(g);
       
        if (!editor.getFigura().getFormas().isEmpty()) {
            for(int c = 0; c<editor.getFigura().getFormas().size();c++) {
               
                try {
                    editor.getFigura().desenharForma(g,c);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Forma inexistente!", "Erro", WARNING_MESSAGE);
                }
            }
        }
        
    }
    
    public int getXTela() {
        return xTela;
    }
    
    public int getYTela() {
        return yTela;
    }
    
    public int getX1() {
        return x1;
    }
    
    public int getY1() {
        return y1;
    }
    
    public int getX2() {
        return x2;
    }
    
    public int getY2() {
        return y2;
    }
    
    public Editor getEditor() {
        return editor;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
